import type { Cursor, Enum, User } from '../index.js';

/**
 * A timeline tweet. If this tweet is a reply under the currently focused tweet, it will be a `Conversation` instead
 * 
 * @see {@link Conversation}
 */
export interface Tweet {
    __typename: 'Tweet',
    id: string,
    author: User,
    /** Birdwatch note on this tweet */
    birdwatch_note?: {
        id: string,
        /** The full text of the note */
        text: string,
        lang: string,
        /** `true` is the note is written in a different language than the client language, and is a reasonable length */
        translatable: boolean,
        /** `true` if this note is publicly displayed on the tweet. It can only be `false` if you are a Birdwatch contributor */
        public: boolean
    },
    /** `true` if you bookmarked this tweet */
    bookmarked: boolean,
    /** Amount of users that bookmarked this tweet */
    bookmarks_count: number,
    /** Card content of the tweet. Can be an embed, poll, audiospace, etc */
    card?: CardKind,
    // community: {},
    created_at: string,
    /**  */
    editing: {
        allowed: boolean,
        allowed_until: string,
        remaining_count: number,
        /** The current id of this tweet and ids of all previous edits */
        tweet_ids: string[]
    },
    /** `true` if the tweet is so long that the full text is not displayed normally. `this.text` will still contain all text */
    expandable: boolean,
    /**
     * `true` if any media in the tweet is labelled as ai generated
     * 
     * @deprecated This property is redundant because it's just `tweet.media.some(media => media.ai_generated)`
     */
    has_ai_generated_image: boolean,
    /** `true` if the tweet has an active or pending Birdwatch note */
    has_birdwatch_note: boolean,
    /** `true` the tweet has a Grok conversation embed */
    has_grok_chat_embed: boolean,
    /**
     * `true` if the hidden replies badge should be displayed on a tweet
     * 
     * @deprecated Twitter no longer supports this feature on newer GraphQL endpoints
     */
    has_hidden_replies: boolean,
    /** `true` if this tweet is quoting another tweet */
    has_quoted_tweet: boolean,
    lang: string,
    /** `true` if you liked this tweet */
    liked: boolean,
    /** Amount of users that liked the tweet */
    likes_count: number,
    media: TweetMedia[],
    /** @deprecated Renamed to `source` */
    platform: any,
    /** The platform the tweet has posted from */
    source: string,
    /** Amount of users that are quote tweeting the tweet */
    quote_tweets_count: number,
    /**
     * The quoted tweet, if it exists. May be `undefined` even if `has_quoted_tweet` is `true` and `quoted_tweet_id` is a `string`, to avoid too many recursions. Due to issues on Twitter's end, sometimes the tweet is not sent in the response data, so this property may be `undefined` for no reason
     */
    quoted_tweet?: Tweet,
    /** Id of the quoted tweet, if it exists */
    quoted_tweet_id?: string,
    /** Amount of users that replied to the tweet */
    replies_count: number,
    /** The username of the user the tweet is in reply to */
    replying_to_username?: string,
    /** `true` if you retweeted this tweet */
    retweeted: boolean,
    /** Amount of users that retweeted the tweet */
    retweets_count: number,
    /** The full text of the tweet, including user mentions in the beginning of replies. If the tweet is a note tweet, this property will contain the expanded text instead of the 280 character preview */
    text: string,
    translatable: boolean,
    /** Amount of views the tweet has. May be `undefined` if the tweet predates view tracking */
    views_count?: number,
    /** Visibility status */
    visibility_limited?: TweetLimitedReason
}



export interface TweetImage {
    __typename: 'Image',
    id: string,
    /** `true` if the media has been generated by Grok in-app */
    ai_generated: boolean,
    /** Alt text set on the media by the author of the tweet */
    alt_text?: string,
    /** 
     * `true` the media is available to view. May be `false` if the media has been deleted or copyright claimed
     * 
     * @deprecated Replaced by `availability`
     */
    available: boolean,
    availability: TweetMediaAvailability,
    /** Original width and height of the media */
    size: {
        width: number,
        height: number
    },
    /** URL of the image, or shorthand for the highest quality video variant */
    url: string
}

export interface TweetVideo extends Omit<TweetImage, '__typename'> {
    __typename: 'Video',
    aspect_ratio: [number, number],
    /** Duration in milliseconds. Always `0` on gifs */
    duration: number,
    /** URL for the video's thumbnail */
    thumbnail_url: string,
    /** Variants for all video's qualities, from lowest to highest */
    variants: Array<{
        bitrate?: number,
        content_type: string,
        url: string
    }>
}

export interface TweetGif extends Omit<TweetVideo, '__typename'> {
    __typename: 'Gif'
}

/**
 * Availability status of a media
 * 
 * @enum
 */
export const TweetMediaAvailability = {
    OK: 'OK',
    Copyright: 'Copyright',
    GeoBlocked: 'GeoBlocked',
    Other: 'Other'
} as const;
export type TweetMediaAvailability = Enum<typeof TweetMediaAvailability>;

/**
 * Tweet media
 */
export type TweetMedia = TweetImage | TweetGif | TweetVideo;



/**
 * Retweet that contains the retweeted tweet within
 */
export interface Retweet {
    __typename: 'Retweet',
    id: string,
    tweet: Tweet,
    user: User
}



/**
 * Conversation that can contain multiple tweets
 */
export interface Conversation {
    __typename: 'Conversation',
    items: (Tweet | TweetTombstone | Cursor)[]
}



/**
 * A deleted or unavailable tweet that is represented with a tombstone in-app
 */
export interface TweetTombstone {
    __typename: 'TweetTombstone',
    /** Reason for the tweet's unavailability */
    reason: TweetUnavailableReason
}

/**
 * Tweet unavailability reasons
 * 
 * @enum
 */
export const TweetUnavailableReason = {
    /** ID verification is required to view this tweet. Restricted server-side */
    AgeVerificationRequired: 'AgeVerificationRequired',
    /** Author has protected their tweets */
    AuthorProtected: 'AuthorProtected',
    /** Author has been suspended */
    AuthorSuspended: 'AuthorSuspended',
    /** Author has deactivated or is otherwise unavailable */
    AuthorUnavailable: 'AuthorUnavailable',
    /** Tweet has been deleted */
    Deleted: 'Deleted',
    /** Tweet has been removed because it violated Twitter's rules */
    ViolatedRules: 'ViolatedRules',
    /** Tweet has been withheld in your country or all countries */
    Withheld: 'Withheld',
    /** @default */
    Unavailable: 'Unavailable'
} as const;
export type TweetUnavailableReason = Enum<typeof TweetUnavailableReason>;

/**
 * Tweet limitation status
 * 
 * @enum
 */
export const TweetLimitedReason = {
    /** Tweet is violent and Twitter has restricted its visibility */
    Violent: 'Violent',
    /** Author has limited the replies */
    LimitedReplies: 'LimitedReplies',
    /** Author has blocked you */
    Blocked: 'Blocked'
} as const;
export type TweetLimitedReason = Enum<typeof TweetLimitedReason>;

export type TweetKind = Tweet | Retweet | Conversation | TweetTombstone;



export interface DraftTweet {
    id: string,
    text: string,
    media_ids: string[],
    thread: {
        text: string,
        media_ids: string[]
    }[]
}

export interface ScheduledTweet extends DraftTweet {
    send_at: string
}



export interface MediaUploadInit {
    media_id: number,
    media_id_string: string,
    expires_after_secs: number,
    media_key: string
}

/**
 * Data about an uploaded media file
 */
export interface Media {
    id: string,
    media_key: string,
    /** Size of the media in bytes */
    bytes: number,
    /** Mime type of the media, defaults to `video/mp4` for gifs, since Twitter stores gifs as mp4, but doesn't actually return any mime type on gif uploads specifically */
    content_type?: string,
    /** Amount of seconds left until the media id expires */
    expires_in: number,
    /** Width of the image in pixels, `undefined` if the given media is a video or gif */
    width?: number,
    /** Height of the image in pixels, `undefined` if the given media is a video or gif */
    height?: number,
    /** Information about how Twitter handled the uploaded media */
    processing?: {
        /**
         * `succeeded` means the media has been uploaded  
         * `failed` means the media has been rejected  
         * `pending` means a separate STATUS request needs to be made to get missing information
         */
        state: 'succeeded' | 'failed' | 'pending',
        progress?: number
    }
}

/**
 * Shared card data
 */
interface Card {
    card_name: string,
    card_url: string
}

export interface CardImage {
    width: number,
    height: number,
    url: string
}



/**
 * Embed of a website in a tweet
 */
export interface Embed extends Card {
    __typename: 'Embed',
    description: string,
    domain: string,
    thumbnail?: CardImage,
    title: string
}

/**
 * Poll with 2-4 choices
 */
export interface Poll extends Card {
    __typename: 'Poll',
    choices: PollChoice[],
    /** Duration of the poll in seconds */
    duration: number,
    ends_at: string,
    total_votes_count: number
}

/**
 * Choice on a poll
 */
export interface PollChoice {
    text: string,
    image?: CardImage,
    votes_count: number,
}

/**
 * Stream broadcast in a tweet
 */
export interface BroadcastCard extends Card {
    __typename: 'Broadcast',
    /** Author of the embedded broadcast */
    author: User,
    /** `true` if the broadcast has ended */
    ended: boolean,
    id: string,
    /** Id of the broadcast video media */
    media_id: string,
    media_key: string,
    thumbnail?: CardImage,
    title: string,
    width: number,
    height: number
}

/**
 * Audiospace or audio message in a tweet
 * 
 * @todo
 */
export interface Audiospace extends Card {
    __typename: 'Audiospace',
    author: User
}

export type CardKind = Audiospace | BroadcastCard | Embed | Poll;
