import type { Enum, Model, PartialBy, Type, Wrapped } from '../internal/index.js';
import { match } from '../../utils/index.js';

export interface TweetImage extends Type<'Image'> {
    id: bigint,
    /** Alt text set on the media by the author of the tweet */
    altText?: string,
    availability: TweetMediaAvailability,
    /** `true` if the media has been generated by Grok in-app */
    isAiGenerated: boolean,
    /** Original width and height of the media */
    size: {
        width: number,
        height: number
    },
    /** URL of the image, or shorthand for the highest quality video variant */
    url: string
}
export const TweetImage: Wrapped<TweetMedia, Model<TweetImage>> = {
    async new(_, value) {
        return {
            __typename: 'Image',
            id: BigInt(value.id_str),
            altText: value.ext_alt_text || undefined,
            availability: match(value.ext_media_availability?.reason, [
                [undefined, TweetMediaAvailability.Available],
                ['DMCAed', TweetMediaAvailability.Copyright],
                ['Geoblocked', TweetMediaAvailability.GeoBlocked]
            ], TweetMediaAvailability.Other),
            isAiGenerated: !!value.media_results?.result?.grok_image_annotation,
            size: {
                width: value.original_info.width,
                height: value.original_info.height
            },
            url: value.media_url_https
        };
    },
    assert(value) {
        if (value.__typename !== 'Image') {
            throw new Error();
        }

        return value;
    }
};

export interface TweetVideo extends Omit<TweetImage, '__typename' | 'altText'>, Type<'Video'> {
    aspectRatio: [number, number],
    /** Duration in milliseconds */
    duration: number,
    /** URL for the video's thumbnail */
    thumbnailUrl: string,
    /** Variants for all video's qualities, from lowest to highest */
    variants: {
        bitrate?: number,
        contentType: string,
        url: string
    }[]
}
export const TweetVideo: Wrapped<TweetMedia, Model<TweetVideo>> = {
    async new(fmt, value) {
        let image = await fmt.next(TweetImage, value);
        delete image.altText;

        return {
            ...image,
            __typename: 'Video',
            aspectRatio: value.video_info?.aspect_ratio ?? [1, 1],
            duration: value.video_info?.duration_millis || 0,
            thumbnailUrl: value.media_url_https,
            variants: value.video_info.variants.map((variant: any) => ({
                bitrate: variant.bitrate,
                contentType: variant.content_type,
                url: variant.url
            }) satisfies TweetVideo['variants'][number]),
            url: value.video_info.variants.at(-1).url
        };
    },
    assert(value) {
        if (value.__typename !== 'Video') {
            throw new Error();
        }

        return value;
    }
};

export interface TweetGif extends Omit<TweetVideo, '__typename' | 'duration'>, Type<'Gif'> {}
export const TweetGif: Wrapped<TweetMedia, Model<TweetGif>> = {
    async new(fmt, value) {
        let video: PartialBy<TweetVideo, 'duration'> = await fmt.next(TweetVideo, value);
        delete video.duration;

        return {
            ...video,
            __typename: 'Gif'
        };
    },
    assert(value) {
        if (value.__typename !== 'Gif') {
            throw new Error();
        }

        return value;
    }
};

/**
 * Availability status of a media
 * 
 * @enum
 */
export const TweetMediaAvailability = {
    Available: 'Available',
    Copyright: 'Copyright',
    GeoBlocked: 'GeoBlocked',
    Other: 'Other'
} as const;
export type TweetMediaAvailability = Enum<typeof TweetMediaAvailability>;

/**
 * Tweet media
 */
export type TweetMedia = TweetImage | TweetGif | TweetVideo;
export const TweetMedia: Model<TweetMedia> = {
    async new(fmt, value) {
        return await fmt.next(
            match<string, Model<TweetMedia>>(value.type, [
                ['video', TweetVideo],
                [['gif', 'animated_gif'], TweetGif]
            ], TweetImage),
            value
        );
    }
};



export interface MediaUploadInit {
    media_id: number,
    media_id_string: string,
    expires_after_secs: number,
    media_key: string
}

/**
 * Data about an uploaded media file
 */
export interface Media {
    id: bigint,
    mediaKey: string,
    /** Size of the media in bytes */
    bytes: number,
    /** Mime type of the media, defaults to `video/mp4` for gifs, since Twitter stores gifs as mp4, but doesn't actually return any mime type on gif uploads specifically */
    contentType?: string,
    /** Amount of seconds left until the media id expires */
    expiresIn: number,
    /** Width of the image in pixels, `undefined` if the given media is a video or gif */
    width?: number,
    /** Height of the image in pixels, `undefined` if the given media is a video or gif */
    height?: number,
    /** Information about how Twitter handled the uploaded media */
    processing?: {
        /**
         * `succeeded` means the media has been uploaded  
         * `failed` means the media has been rejected  
         * `pending` means a separate STATUS request needs to be made to get missing information
         */
        state: 'succeeded' | 'failed' | 'pending',
        progress?: number
    }
}
