export type Flags = Partial<{
    responsive_web_graphql_timeline_navigation_enabled: boolean,
    responsive_web_birdwatch_note_request_sources_enabled: boolean,
    highlights_tweets_tab_ui_enabled: boolean,
    responsive_web_edit_tweet_api_enabled: boolean,
    responsive_web_birdwatch_media_notes_enabled: boolean,
    responsive_web_enhance_cards_enabled: boolean,
    responsive_web_grok_community_note_translation_is_enabled: boolean,
    subscriptions_upsells_api_enabled: boolean,
    responsive_web_birdwatch_enforce_author_user_quotas: boolean,
    longform_notetweets_inline_media_enabled: boolean,
    responsive_web_birdwatch_note_limit_enabled: boolean,
    rweb_tipjar_consumption_enabled: boolean,
    standardized_nudges_misinfo: boolean,
    creator_subscriptions_quote_tweet_preview_enabled: boolean,
    responsive_web_grok_image_annotation_enabled: boolean,
    profile_label_improvements_pcf_label_in_post_enabled: boolean,
    responsive_web_grok_analyze_post_followups_enabled: boolean,
    responsive_web_twitter_article_tweet_consumption_enabled: boolean,
    verified_phone_label_enabled: boolean,
    responsive_web_grok_analyze_button_fetch_trends_enabled: boolean,
    responsive_web_jetfuel_frame: boolean,
    responsive_web_birdwatch_url_notes_enabled: boolean,
    longform_notetweets_consumption_enabled: boolean,
    c9s_tweet_anatomy_moderator_badge_enabled: boolean,
    responsive_web_grok_imagine_annotation_enabled: boolean,
    responsive_web_graphql_skip_user_profile_image_extensions_enabled: boolean,
    subscriptions_verification_info_verified_since_enabled: boolean,
    responsive_web_birdwatch_translation_enabled: boolean,
    longform_notetweets_rich_text_read_enabled: boolean,
    subscriptions_verification_info_is_identity_verified_enabled: boolean,
    premium_content_api_read_enabled: boolean,
    subscriptions_management_fetch_next_billing_time: boolean,
    responsive_web_birdwatch_signup_prompt_enabled: boolean,
    responsive_web_birdwatch_mobile_nav_setting_enabled: boolean,
    responsive_web_birdwatch_note_request_download_enabled: boolean,
    responsive_web_birdwatch_note_internal_insights_enabled: boolean,
    hidden_profile_subscriptions_enabled: boolean,
    responsive_web_grok_analysis_button_from_backend: boolean,
    rweb_video_screen_enabled: boolean,
    responsive_web_grok_show_grok_translated_post: boolean,
    spaces_2022_h2_clipping: boolean,
    view_counts_everywhere_api_enabled: boolean,
    creator_subscriptions_tweet_preview_api_enabled: boolean,
    responsive_web_grok_community_note_auto_translation_is_enabled: boolean,
    tweet_awards_web_tipping_enabled: boolean,
    responsive_web_birdwatch_top_contributor_enabled: boolean,
    responsive_web_twitter_article_notes_tab_enabled: boolean,
    tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled: boolean,
    responsive_web_birdwatch_fast_notes_badge_enabled: boolean,
    responsive_web_birdwatch_live_note_enabled: boolean,
    communities_web_enable_tweet_community_results_fetch: boolean,
    graphql_is_translatable_rweb_tweet_is_translatable_enabled: boolean,
    subscriptions_feature_can_gift_premium: boolean,
    responsive_web_profile_redirect_enabled: boolean,
    freedom_of_speech_not_reach_fetch_enabled: boolean,
    spaces_2022_h2_spaces_communities: boolean,
    subscriptions_marketing_page_fetch_promotions: boolean,
    responsive_web_grok_share_attachment_enabled: boolean,
    articles_preview_enabled: boolean
}>;

export const birdwatch = {
    responsive_web_birdwatch_live_note_enabled: true,
    responsive_web_birdwatch_enforce_author_user_quotas: true,
    responsive_web_birdwatch_media_notes_enabled: true,
    responsive_web_birdwatch_url_notes_enabled: true,
    responsive_web_grok_community_note_translation_is_enabled: true,
    responsive_web_birdwatch_fast_notes_badge_enabled: true,
    responsive_web_birdwatch_note_internal_insights_enabled: true,
    responsive_web_grok_community_note_auto_translation_is_enabled: false,
    responsive_web_graphql_timeline_navigation_enabled: true,
    payments_enabled: false,
    profile_label_improvements_pcf_label_in_post_enabled: true,
    responsive_web_profile_redirect_enabled: false,
    rweb_tipjar_consumption_enabled: true,
    verified_phone_label_enabled: false,
    responsive_web_graphql_skip_user_profile_image_extensions_enabled: false
};

export const short = {
    profile_label_improvements_pcf_label_in_post_enabled: true,
    responsive_web_profile_redirect_enabled: false,
    rweb_tipjar_consumption_enabled: true,
    verified_phone_label_enabled: false,
    responsive_web_graphql_skip_user_profile_image_extensions_enabled: false,
    responsive_web_graphql_timeline_navigation_enabled: true
} satisfies Flags;

export const timeline = {
    rweb_video_screen_enabled: false,
    profile_label_improvements_pcf_label_in_post_enabled: true,
    responsive_web_profile_redirect_enabled: false,
    rweb_tipjar_consumption_enabled: true,
    verified_phone_label_enabled: false,
    creator_subscriptions_tweet_preview_api_enabled: true,
    responsive_web_graphql_timeline_navigation_enabled: true,
    responsive_web_graphql_skip_user_profile_image_extensions_enabled: false,
    premium_content_api_read_enabled: false,
    communities_web_enable_tweet_community_results_fetch: true,
    c9s_tweet_anatomy_moderator_badge_enabled: true,
    responsive_web_grok_analyze_button_fetch_trends_enabled: false,
    responsive_web_grok_analyze_post_followups_enabled: true,
    responsive_web_jetfuel_frame: false,
    responsive_web_grok_share_attachment_enabled: true,
    articles_preview_enabled: true,
    responsive_web_edit_tweet_api_enabled: true,
    graphql_is_translatable_rweb_tweet_is_translatable_enabled: true,
    view_counts_everywhere_api_enabled: true,
    longform_notetweets_consumption_enabled: true,
    responsive_web_twitter_article_tweet_consumption_enabled: true,
    tweet_awards_web_tipping_enabled: false,
    responsive_web_grok_show_grok_translated_post: false,
    responsive_web_grok_analysis_button_from_backend: true,
    creator_subscriptions_quote_tweet_preview_enabled: false,
    freedom_of_speech_not_reach_fetch_enabled: true,
    standardized_nudges_misinfo: true,
    tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled: true,
    longform_notetweets_rich_text_read_enabled: true,
    longform_notetweets_inline_media_enabled: true,
    responsive_web_grok_imagine_annotation_enabled: false,
    responsive_web_grok_community_note_auto_translation_is_enabled: false,
    responsive_web_grok_image_annotation_enabled: false,
    responsive_web_enhance_cards_enabled: true
} satisfies Flags;

export const user = {
    hidden_profile_subscriptions_enabled: true,
    profile_label_improvements_pcf_label_in_post_enabled: true,
    responsive_web_profile_redirect_enabled: false,
    rweb_tipjar_consumption_enabled: true,
    verified_phone_label_enabled: false,
    subscriptions_verification_info_is_identity_verified_enabled: true,
    subscriptions_verification_info_verified_since_enabled: true,
    highlights_tweets_tab_ui_enabled: true,
    responsive_web_twitter_article_notes_tab_enabled: true,
    subscriptions_feature_can_gift_premium: true,
    creator_subscriptions_tweet_preview_api_enabled: true,
    responsive_web_graphql_skip_user_profile_image_extensions_enabled: false,
    responsive_web_graphql_timeline_navigation_enabled: true
} satisfies Flags;
